name: dotnet package

on: [push]

env:
  AZURE_WEBAPP_NAME: weather-appservice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK '5.0.x'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput='./results/' /p:CoverletOutputFormat=cobertura --logger "trx;LogFileName=test-results.trx" --no-restore --verbosity q
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: XUnit Tests
          path: ./*/TestResults/*.trx
          reporter: dotnet-trx
      - name: dotnet publish
        run: |
            dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_NAME }}
            
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          name: 'Deploy to Azure weather app'
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './${{ env.AZURE_WEBAPP_NAME }}'
